---
name: "semver-generator"
description: "Github Action for generating a semver version"
author: "Dokku"
branding:
  icon: "tag"
  color: "blue"
inputs:
  bump:
    description: "The type of bump to perform (major, minor, patch)"
    required: true
  input:
    description: "The input version to bump"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  entrypoint: "/usr/local/bin/entrypoint"
  env:
    SEMVER_GENERATOR_BUMP: ${{ inputs.bump }}
    SEMVER_GENERATOR_INPUT: ${{ inputs.input }}
